### ISSUE TITLE
Bot not updating query every 15 seconds

### ISSUE THREAD

**Issue by xLeviNx** [DiscordGSM/DiscordGSM#3]
I was testing DiscordGSM with the gamedigQuery
For some reason, the discord bot does not update the query every 15 seconds. It occasionally updates every few minutes, otherwise it is super delayed.

**Comment by BattlefieldDuck** [comment]
It queries every 15 seconds in the background. If the data is the same, it will not update the message embed. Speak in another way, It only updates the message embed if the data is changed.

**Comment by xLeviNx** [comment]
![image](https://user-images.githubusercontent.com/48465241/80316122-f6fa5a80-87c9-11ea-9451-8f11135ae0a9.png)

I pasted a copy of it. There is currently 17 players in the server, but as of me posting this now to it updating, its been over 25+ minutes since last update

**Comment by BattlefieldDuck** [comment]
@xLeviNx please update to v1.5.0, many errors have fixed and new features have added. Thanks.
