### ISSUE TITLE
Bot crashed after add/replace server.json

### ISSUE THREAD

**Issue by mrnoahfink** [DiscordGSM/DiscordGSM#6]
I am using Heroku after bot online and working commands. after that, I replace it with my own server.json then suddenly it crashed and will not back online. Even I try to replace back to normal Github and your "server.json". It never recovers. I did test both Dev and Stable.

**Comment by mrnoahfink** [comment]
Here Error Log for Heroku 
[kpgtf2statuserver-logs-1602955622235.txt](https://github.com/DiscordGSM/DiscordGSM/files/5396120/kpgtf2statuserver-logs-1602955622235.txt)
Stable

**Comment by Alpha-20** [comment]
Might be an error in your server.json file. The bot crashes if there's an error in your server.json file. Better to join their discord to contact their support team.

**Comment by mrnoahfink** [comment]
Well, I try to fix something in server.json and no luck. 

Can you check and see that if I did something wrong? (btw GitHub doesn't support json files) 

[statuserver.txt](https://github.com/DiscordGSM/DiscordGSM/files/5404508/statuserver.txt)

**Comment by Alpha-20** [comment]
Better to get it checked from the developer himself. here's the discord link https://discord.gg/Sp36ss

**Comment by mrnoahfink** [comment]
I did join a couple of days ago lol. anyway, I did mention that.

**Comment by TandelK** [comment]
@mrnoahfink I can see that after every servers added in servers.json you forgot to add `,` in the end. As per the  JSON Format it should be like this

```
[
    {
        "type": "SourceQuery",
        "game": "Team Fortress 2",
        "addr": "",
        "port": 27015,
        "channel": ,
        "image_url": ""
    },
   {
        "type": "SourceQuery",
        "game": "Team Fortress 2",
        "addr": "",
        "port": 27025,
        "channel": ,
        "image_url": ""
    }
]
```

After the ending of each section you will have to mention `,` in the end except for the last one.

**Comment by mrnoahfink** [comment]
Thanks! Now I don't have any problem! I realize that I just don't need , the last one. Thanks so much for helping!
